name: brimo_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8

  # State Management & Services
  shared_preferences: ^2.2.2

  # UI & Animasi
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0

  # Kamera
  camera: ^0.11.0+1
  permission_handler: ^11.3.1

  # Utilitas
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/