// File generated by FlutterFire CLI.
// DO NOT MODIFY.
//
// This file is generated from the Firebase project mbanking-brimo
// It contains a unique set of identifiers for this project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      // Konfigurasi untuk Windows belum disediakan, bisa ditambahkan jika perlu.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB9ES_xJz2exInQY6Mr00MPu1ps_bMnwxk",
    appId: "1:277203033863:web:608043ce10956e7147afa2",
    messagingSenderId: "277203033863",
    projectId: "mbanking-brimo",
    authDomain: "mbanking-brimo.firebaseapp.com",
    storageBucket: "mbanking-brimo.appspot.com", // Disesuaikan, biasanya .appspot.com
    measurementId: "G-5TBY52YJTY",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB9ES_xJz2exInQY6Mr00MPu1ps_bMnwxk", // API Key biasanya sama untuk Android
    appId: "1:277203033863:android:YOUR_ANDROID_APP_ID_HASH", // Ganti dengan ID asli dari console
    messagingSenderId: "277203033863",
    projectId: "mbanking-brimo",
    storageBucket: "mbanking-brimo.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB9ES_xJz2exInQY6Mr00MPu1ps_bMnwxk", // API Key biasanya sama untuk iOS
    appId: "1:277203033863:ios:YOUR_IOS_APP_ID_HASH", // Ganti dengan ID asli dari console
    messagingSenderId: "277203033863",
    projectId: "mbanking-brimo",
    storageBucket: "mbanking-brimo.appspot.com",
    iosBundleId: "com.example.brimoClone", // Ganti dengan bundle ID Anda
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB9ES_xJz2exInQY6Mr00MPu1ps_bMnwxk", // API Key biasanya sama untuk macOS
    appId: "1:277203033863:ios:YOUR_MACOS_APP_ID_HASH", // Ganti dengan ID asli dari console
    messagingSenderId: "277203033863",
    projectId: "mbanking-brimo",
    storageBucket: "mbanking-brimo.appspot.com",
    iosBundleId: "com.example.brimoClone.runner", // Ganti dengan bundle ID Anda
  );
}
